типы данных
dl-academy-edu/yo-shulgina-tatiana-3 pull request #1
Opened 2023-03-24 09:02 UTC by TatianaShulgina2022

2023-03-24 17:24 UTC, AlexFGeeR requested changes
Хорошо, правки есть, но не критичные, так что продолжай в том же духе и лучше!

2023-03-24 17:24 UTC, AlexFGeeR commented on source/js/app.js
> +console.log(Number(cost), String(cost), Boolean(cost));
Код который пишется как решение задачек, которые не относятся к проекту нужно помещать в другой файл. А именно нужно рядом с папкой `source` создать другую папку, например, `homeworks` и там уже создавать папки под лекции, например, `lecture_1` и писать какой-либо код, создавая отдельный файл `.js` и `.html`.

2023-03-24 17:24 UTC, AlexFGeeR commented on source/js/app.js
> +let abc = 150;
### Нейминг
Не информативное наименование переменной. Исходя из названия `abc`, я как программист, не могу предположить что это за переменная и что она в теории может в себе хранить.

2023-03-24 17:24 UTC, AlexFGeeR commented on source/js/app.js
> +let what = true;
### Нейминг
Не информативное наименование переменной. Исходя из названия `what`, я как программист, не могу предположить что это за переменная и что она в теории может в себе хранить. Также обычно переменные с типом данных `Boolean` принято наименование начиная с частички `is`, `has` и т.д.
Таким образом, пример хорошего нейминга: `isChickenFly`, потому что тут сразу понятно что означает логическое значение внутри этой переменной.

2023-03-24 17:24 UTC, AlexFGeeR commented on source/js/app.js
> +let cost = {
### Нейминг
Наименование переменной в виде `cost`, представляет мне представление о том, что там храниться число с ценной чего-либо, но по факту я тут получаю какой-то объект. Лучше преобразовать нейминг следующим образом: `let product = {name: "juice", price: 50}`. Таким образом, мы видимо что это у нас объект продукта с его наименованием и ценой.

2023-03-26 18:23 UTC, TatianaShulgina2022 commented
исправила по д/з 1

2023-03-30 18:23 UTC, AlexFGeeR reviewed
Домашку первую принимаю, жду оставшиеся задачи по второй.

2023-04-03 14:48 UTC, AlexFGeeR approved these changes
Доделай 3 и 4 задачку.

2023-04-03 14:48 UTC, AlexFGeeR commented on homeworks/2 lecture/script.js
> +  if (i%4 == 0) continue;
### Стайлгайд
Отступы между `i` и `4`. Также стоит использовать строгое равенство.

2023-04-03 14:48 UTC, merged